# Dockerfile.worker.dev

FROM ubuntu:latest

# 1) System-Dependencies
RUN apt-get update && \
    apt-get install -y \
      python3 \
      python3-pip \
      python3-venv \
      libpq-dev \
      libcurl4-openssl-dev \
      libssl-dev \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN python3 -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

RUN pip install --upgrade pip && \
    pip install pipenv

WORKDIR /app
COPY Pipfile Pipfile.lock ./
COPY . .

RUN pipenv install --system --deploy

ENTRYPOINT ["/app/bin/docker-entrypoint"]
CMD ["worker"]
